"""make user_id non-nullable in posts

Revision ID: 510ed939e147
Revises: 0ee79f9843b9
Create Date: 2024-01-18 17:01:23.151363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510ed939e147'
down_revision = '0ee79f9843b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
